### ISSUE TITLE
Vice-county selection [show boundaries on review]

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#41]
The vice-county picker for ambiguous gridrefs is useful when the VC field is not already populated, but shouldn't re-prompt if a valid vc is already filled in.

E.g. if Oxfordshire is already set, then entering SU6189 as the grid-square should prompt me to say whether I meant Oxfordshire or Berkshire.

A secondary problem is that the VC field can subsequently be set to a county that does not match the gridsquare.

What happens if, through the use of precise gridrefs records for a square should be assigned to two different counties?

See #3 for umbrella issue.

**Comment by sacrevert** [comment]
In #7 we suggested that we would require users to fill in the card twice for different VCs (in order to save on development resources). If we stick with that approach, then I suppose we just need to make sure that the precise, non-target VC record is rejected with a helpful error message.

**Comment by johnvanbreda** [comment]
I've added code so that if you enter a specific VC first then add a grid square which overlaps the boundary, it no longer asks you to confirm which VC you mean, it just keeps the one you entered. This is in the develop branch ready to go live at the next feature update.
I think there are 2 other separate warnings alluded to in the rest of this issue so I just want to check if either or both are correct:
1) Enter a grid ref, then change the auto-selected VC to a wrong one so the VC and grid ref do not match. Should this give an error on save? (I assume yes)
2) Enter a grid ref and use the auto-selected VC. Enter some records, one or more of which have a detailed grid ref that is not in the VC. Should this give an error on save?

**Comment by sacrevert** [comment]
1. Enter a grid ref, then change the auto-selected VC to a wrong one so the VC and grid ref do not match. 
 Should this give an error on save? (I assume yes)
**OLP: Yes, it seems to me that that is what Tom describes**

2. Enter a grid ref and use the auto-selected VC. Enter some records, one or more of which have a detailed grid ref that is not in the VC. Should this give an error on save?
**OLP: Yes, unless we currently have enough resources to allow for a situation where the user can amend the VC at the record level for those specific instances where they do no match the prev. selected VC. If we do, then I suppose we still need the system to do a check that the grid-ref/VC edits match.**
**if we don't have the resources for this, I can create a new issue for future enhancement, and an error message saying "Please enter this out-of-VC record using a separate card." can appear**

Tagging @kwal2 @japonicus and @DavidRoy for info (no need to comment unless desired).

**Comment by johnvanbreda** [comment]
I've implemented the first point above - if you enter a grid ref then change the auto-selected VC to a different one that doesn't overlap the grid ref you get a validation error.

For the finer grid refs, we are already validating they are inside the main sample grid ref so are unlikely to get transpositions and other wildly incorrect refs. So the only situation we want to avoid is where the main sample has a VC, but a finer grid ref has strayed across the border. This gets quite complex because we could also have finer grid refs that overlap the border. I am not sure it is worth the effort at the moment, so I will just leave this open for future reference unless I hear otherwise.

**Comment by sacrevert** [comment]
Yes, I see what you mean. Would a simple enhancement be to show vice-county boundaries on the review map?

**Comment by johnvanbreda** [comment]
Yes, I think that is no more than an hour's work. Let me know if you want me to do that.

**Comment by sacrevert** [comment]
@DavidRoy is this OK? Not sure if this will have benefits for other sites?

**Comment by DavidRoy** [comment]
I agree that this would be useful.  @johnvanbreda please go ahead with this

**Comment by sacrevert** [comment]
When you implement this, can you also add some fixed text somewhere (e.g. below the review map but above the summary data) that says:
"Please check that any fine-scale records that you have made are assigned to the correct vice-county."

thanks!

**Comment by johnvanbreda** [comment]
The chosen vice county boundary is now loaded onto the map. Just need to add the suggested text from the above comment to the review tab.

**Comment by sacrevert** [comment]
Assuming that these issues will be dealt with by BBS funded work
