### ISSUE TITLE
Plant status options

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#51]
Nested in #3 

Current status options do not clearly map to BSBI Atlas 2020 recording advice.

From this doc (http://bsbi.org/Atlas_2020_Guidance_for_VCRs_v4.pdf)
>"2.7.Status
For nationally native taxa the status of an occurrence (i.e. the origin of a plant at a particular location) need only be recorded if it has clearly been, or is likely to have been, introduced to that particular locality. Therefore the vast majority of occurrences of native taxa can be crossed off
without further comment. Where the recorder feels that a native species has been planted or introduced to the area then they should use one of the codes below. Introduced (non-native) species should also be recorded in this way with the exception of aliens that are widely established (e.g. Sycamore). These can be crossed off without further comment.
E Established (a taxon which has been present in the wild for at least 5 years and is spreading vegetatively or is effectively reproducing by seed)
S Surviving (present in the wild for at least 5 years but neither spreading vegetatively nor reproducing effectively from seed)
C Casual (present briefly, i.e. for less than five years, or intermittently)
P Planted deliberately, not established"

Can we change these options? Also flagging @kwal2 and @japonicus

**Comment by DavidRoy** [comment]
Yes.  BSBI to decide. @kwal2

**Comment by kwal2** [comment]
I would change the status categories to the following:

Native
Unknown
Introduced
Introduced - planted
Introduced - surviving
Introduced - casual
Introduced - established
Introduced - invasive

That should cover most eventualities. Whilst we are on status I wondered if the status categories could be optimised so that only non-native (introduced) categories come up for non-natives as they will be always by default introduced. This is often important for arhaeophytes as many recorders often consider them as natives and would assign them to native.

**Comment by johnvanbreda** [comment]
Does everyone agree with this list?
Note that implementing functionality based on the non-native flag in UKSI would be a fair bit of work - we can consider this further if everyone agrees its a good idea.

**Comment by sacrevert** [comment]
I do.

I think the additional functionality should be a longer-term aim, given the number of other bugs and tweaks outstanding. I'll add a new issue for that, but I suppose it can be flagged as an 'enhancement' (now issue #52).

**Comment by DavidRoy** [comment]
I agree to kwal's recommendation.  Presumably with no default value?

**Comment by johnvanbreda** [comment]
That's done. We probably can't have a useful default without doing the native/non-native work first, unless we just set it to unknown.

**Comment by DavidRoy** [comment]
agreed.  closing issue

**Comment by japonicus** [comment]
> We probably can't have a useful default without doing the native/non-native work first, unless we just set it to unknown.

The default shouldn't depend on the taxon's national status, because a nationally 'native' taxon can be validly recorded as 'introduced' at a particular site - defaulting to 'native' would be dangerous.

I'm not quite sure of Kevin's plans for status, but I would see 'unknown' as being distinct from 'not recorded' (or blank) and that 'not recorded' should be the default. 'unknown' implies that the recorder was uncertain about status (and that there is reason for doubt) rather than the more common case that the recorder had not assessed status at all.

**Comment by sacrevert** [comment]
@japonicus it seems the default is 'blank' currently. 'blank' is presumably synonymous with 'not recorded'. So, I presume that no changes are needed at this point. I'll add your comment to #52 for future ref though.
