### ISSUE TITLE
Status options filter by non-native UKSI tag

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#52]
Nested in #3 

From Kevin Walker (BSBI)
>Can status categories could be optimised so that only non-native (introduced) categories come up for non-natives as they will be always by default introduced. This is often important for arhaeophytes as many recorders often consider them as natives and would assign them to native.

From JvB
>Note that implementing functionality based on the non-native flag in UKSI would be a fair bit of work - we can consider this further if everyone agrees its a good idea.

**Comment by kwal2** [comment]
I see this as a 'nice to have' rather than an essential feature so not worth the effort currently. The problem is really distinguishing archaeophytes (introductions) from natives. I struggled when entering a few species last night. Note that there will be complications with national statuses if we include Ireland (native Ireland, introduced GB and vice versa).

**Comment by sacrevert** [comment]
From Tom Humphrey for reference (although may not be relevant if blank is always the default):
>The default shouldn't depend on the taxon's national status, because a nationally 'native' taxon can be validly recorded as 'introduced' at a particular site - defaulting to 'native' would be dangerous.
I'm not quite sure of Kevin's plans for status, but I would see 'unknown' as being distinct from 'not recorded' (or blank) and that 'not recorded' should be the default. 'unknown' implies that the recorder was uncertain about status (and that there is reason for doubt) rather than the more common case that the recorder had not assessed status at all.
