### ISSUE TITLE
Irish and GB grids are super-imposed

### ISSUE THREAD

**Issue by japonicus** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#57]
If  an eastern Irish grid square is selected then the map shows a confusing superimposition of both the British and Irish grids, e.g.

 D1235
![screenshot 2017-06-20 15 16 47](https://user-images.githubusercontent.com/207360/27337915-b35e2c3a-55cb-11e7-99bf-5dc4aea6e5c5.png)

Nested under #3

**Comment by johnvanbreda** [comment]
The 2 grid systems do overlap in some parts of Ireland. My proposed solution is for the grid graticules to automatically switch off when a grid square of a different system is input. I.e. the map will initially load with 2 grids, but if you input an Irish grid it will disable the OSGB graticule. Does that sound like it will solve the issue?

**Comment by sacrevert** [comment]
@japonicus to comment (I have no idea).

**Comment by japonicus** [comment]
@johnvanbreda that should solve the problem.

Ideally the grids ought to be clipped to avoid overlaps even when no record's selected, but that's probably more hassle than it's worth.

I have some javascript that does GB and IE grid-clipping for [BSBI maps](http://bsbi.org/maps) and @kazlauskis re-implemented GB (but not Irish) clipping for the apps. Eventually I hope to tidy up and open-source as much as of the BSBI mapping tools as possible (the grid clipping stuff ought to be adaptable to use with iRecord's maps), but that's not done yet.

**Comment by johnvanbreda** [comment]
I think calculating the grid clipping is OK - we already have code which decides whether a point is OSGB or OSIE. However getting the graticule code to draw it nicely might be challenging. 
I've committed code so that if you actively pick a system, enter a grid ref, or select one on the map, then the unused graticules are removed from the map. This will be released in the next feature release.
