### ISSUE TITLE
Plot data importer terminology changes

### ISSUE THREAD

**Issue by andrewvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#58]
Any changes you want to wording of terminology in the plot data importer can be placed in this thread

Nested in #46

**Comment by sacrevert** [comment]
Map screen: What is 'Occurrences :: Zero abundance'? Presumably this is a generic option that can be dropped from the Plant Portal interface?

**AVB Response:** : This is a true or false value that indicates whether we want to explicitly record an abundance of zero in the database, or does an entry of zero not get recorded.
I can hide this for Plant Portal, I think I was mostly guessing what we needed until now. I already have code that hides some of the fields

**OLP Response: Not needed. Please hide.**

**Comment by sacrevert** [comment]
Map screen: 'Occurrences :: Sensitivity precision'
Did we agree that we were going to have a sensitivity blurring option for the Plant Portal? I can't remember. I don't think that we should provide this option off the shelf. We can think about providing it in the future if people ask for it, otherwise I would rather encourage people not to select for their data to be blurred (of course, people can still blur their data prior to loading if they desire).

**AVB Response:** Yes can hide as per above

**Comment by sacrevert** [comment]
Map screen: 'Sample :: Date'
Presumably any type of Recorder 6 date can be mapped to this column? I suppose, then, that it will be down to the guidance documentation to instruct people on how various types of date format should be formatted for this field. Can you confirm?

**AVB Response:** It works using the same date engine that Indicia uses. I think that includes vague dates, it is certainly possible to enter just a year for instance, but I vaguely remember in my days of using Record 6 (a while back!) that it supported vague dates such as "summer 2016" or even something like  "2012-2013", I think Indicia will support these, but I will double check as I haven't tried it. It certainly has code that deals with vague dates

**Comment by sacrevert** [comment]
Map screen: 'Sample :: External key'
So, 'external key' is the user's unique sample reference, right? So, can this be called 'Unique sample ID' instead?
Also, I forget, but my memory is that this only checks for uniqueness against a user's already created samples, not against all sample IDs in the system, and not against other user's samples where those users also have permissions to load new samples against a set of shared plots (i.e. plots that are owned by more than one user). That is fine, I can't really imagine multiple people uploading the same sample data, and even if they did, it wouldn't be the end of the world.

**AVB Response:** Yes it is that, and it does need a name change as per other items in this thread.
As far its behaviour is concerned, this is just used during the importer within the import data itself. It is stored in the database but isn't unique there and doesn't have any specific use in Plant Portal once it is there. So once in the database this isn't actually unique

It is simply used to make sure the occurrences in the importer are going into the correct sample rather than purely having to guess based on data, spatial reference.
If the importer finds rows with the same sample external key (Unique sample ID) but their other sample related columns are inconsistent, then it warns the user.
This warning is new for Plant Portal, the old Indicia importer wouldn't have warned the user and would have created separate samples without warning

**Comment by sacrevert** [comment]
Map screen: 'Sample :: Location (from controlled termlist)'
This is the plot name that the sample is associated with, correct? In which case, can it be called **'Unique plot ID'**? Again, as far as I recall, this is checking against existing plot IDs that the user has permission for, or is it checking against all plots in the system? What happens if a user creates some plots (e.g. plots 1 and 2), but is then later given permission to access some plots created by another user with the same labels? How would the user load new samples to the first plot 1 and not the other plot 1?

**AVB Response**: Again, yes we can change the name.
When importing, the user can only ever import onto an existing plot within their own plot groups.
So in theory someone else could have the same Unique plot ID but because it isn't in your own plot group it won't be imported onto.
Therefore to import onto existing plots it must of been specified to have a plot group.
Plots without a plot group at all cannot have further samples imported onto them, although I supposed you could always make a plot group with just one plot in it, there is no limitation on the number of plot groups a plot can have.
This does indeed leave the scenario where as you say a user could be assigned a plot with a duplicate Unique plot ID into their plot group.
This would need to be handled by the user interface. I think we would have to say if this situation is detected they would need to rename the plot when it is assigned, even if it is just adding some kind of tag on the end. The original user would probably need to be informed of the change, or alternatively depending on how complex we want to get, the original user could continue to see the original name

**OLP response: Fine, good to have identified this potential future issue. Asking the user to rename their plot is the simplest issue, although this does get you into the situation where you might be asking a user to rename a long-established plot because another user has shared a plot group permission containing a plot with the same name, but which was very recently created (in this situation it seems unreasonable to ask user 1 to change their plot name when it had priority). I might be over-thinking this though!** 

**Perhaps a long-term solution would be a check when plot group permissions are shared, with an automatic (but user approved) renaming of plots (e.g. a plot name::spatial ref concatenation) where there are conflicts. Is it worth adding this issue as a future 'enhancement'?**

**Comment by sacrevert** [comment]
Sample custom attributes :: Plant portal spatial reference type (from controlled termlist)
This is the one that will be removed from view and automatically filled based on how the spatial reference is created, I think.

**AVB Response:** OK, noted that this won't be user defined

**Comment by sacrevert** [comment]
Sample custom attributes :: Plant Portal country/vice-county
Would it be possible just to label these as Country and Vice County for simplicity?

I think this is it for the moment -- perhaps you can respond by editing comments. I realise that some of these changes will need to be propagated into error messages etc., but I will not try to document all of these in the other thread ( #59 ) at this point. I can review those later when all of these changes are agreed and implemented. @andrewvanbreda 

**AVB Response:** Yes easy to change attribute name

**Comment by sacrevert** [comment]
Location custom attributes :: Plant Portal plot group text

Again, can this be simplified to 'Plot group ID'?


**AVB Response:** Yes easy to change attribute name

**Comment by andrewvanbreda** [comment]
Also need to change 
"Location (from controlled term list)"
to
'Unique plot ID'

**Comment by andrewvanbreda** [comment]
AVB: On dev fixed names of following attributes
Vice county
Country
Plot width
Plot length
Plot radius
Plot shape
Plot group ID

All of the above had included "Plant Portal" in the title.

Outstanding still:
Removal of Zero Abundance
Removal of Sensitivity Precision
Removal of spatial reference type from user view (and automatically set)
Test vague dates
Change external key column mapping name
Change location column mapping name

**Comment by andrewvanbreda** [comment]
AVB: On my own machine fixed the following in code (not dev until a release):
Removal of Zero Abundance
Removal of Sensitivity Precision
Change external key column mapping name
Change location column mapping name

Outstanding still:
Removal of spatial reference type from user view (and automatically set)
Test vague dates

**Comment by andrewvanbreda** [comment]
@sacrevert Just had a go at double checking the behaviour of vague dates using the standard Indicia importer (which will behave the same way in this regard).
I was fine when I used "2011 to 2012" and "Summer 2013". These appeared in the warehouse correctly on the sample record. 
On grids (which use an ordering), the dates were displayed using precise dates within the warehouse of  "2011-01-01" and "2013-06-01"

This behaviour will be the same for the Plant Portal Plot Importer

**Comment by sacrevert** [comment]
Thanks Andy. I don't think we'll advertise or encourage vague dates like 'Summer YYYY', but certainly dates covering a year or set of years will be necessary. Can I just confirm that for 2011 to 2012, 
>" These appeared in the warehouse correctly on the sample record." 

means a start date of 01/01/2011 and an end date of 31/12/2012 for the occurrence record? @andrewvanbreda thanks

**Comment by andrewvanbreda** [comment]
Yeah I was just trying to remember the kinds of vague dats I used to use trying to break Recorder 6 (on purpose, as a tester). I will check that on my own box where I can actually look in the database, as I was looking in the user interface. As I am in the middle of coding at the moment, the importers on my box aren't operational this very second, but I will give that a go one spare minute sometime. 
I suspect it will work like that otherwise I am not sure where it would get the "2011 to 2012" to display from.

**Comment by sacrevert** [comment]
OK, thanks. Don't spend too much time on this though, I just wanted to make sure that "2011 to 2012" was converted to have appropriate start and end dates, rather than being converted to a single day precision, as you comment about how it displays in the warehouse above kind of implied.

**Comment by andrewvanbreda** [comment]
It is ok, as I will putting further data through the importer anyway, so it only take an extra 30 second to do this

**Comment by andrewvanbreda** [comment]
A run of the actual Plant Portal Importer on my box with the date "2011-2012" reveals the following in the database,
date_start="2011-01-01"
date_end="2012-12-31"
date_type="YY"
