### ISSUE TITLE
Vascular plants card vice county handling

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/BSBI-Card-and-PlantPortal-DEPRECATED-#7]
From the spec:
VC is specified at sample level and is autofilled in an (editable) column on the species data page; but, if the square straddles two or more VCs, a warning message appears and the auto-fill does not occur (but VC number will be a required field) to force entry. If, for example, all records are in one VC, then the user could still use standard Indicia tools to autofill a column.
See #3 for umbrella issue.

**Comment by johnvanbreda** [comment]
I've made some progress on adding the VC at the sample level, but will leave this disabled today so as to not affect any demos over the weekend as I don't think it's perfect yet. Here's what it does:

  - adds a Vice county input box which searches against Vice county names on the first tab.
  - if you click on the map or fill in a grid square, then the vice county auto-fills in. 
  - if 2 vice counties are found (or potentially more) then it pops up and asks you to choose which vice county you were in. Only the picked one will get filled into the vice county field.

I think this is OK apart from the case where you genuinely bashed a square and crossed into 2 vice counties - this approach means you would need to choose 1, or perhaps fill in 2 different forms. I am wondering if there should be an option to save both?

Also perhaps the search/lookup should be by vice county number not name?

At the moment it doesn't do anything at the species record level.

**Comment by sacrevert** [comment]
That sounds good. I think we could probably live with the option of the pop-up question, and then filling in the form twice for your last bullet point. Presumably allowing species level edits for vc membership is a lot more work? I think for the most part recorders would stay inside their vice-county, but filling in the form twice is not that much hassle.

That said, if it is relatively trivial to ask surveyors to choose a vc, but then allow record-level editing, then I suppose we might as well implement. This scenario would obviously argue for using VC numbers rather than names, both as a space saver and to reduce spelling inconsistencies (although I presume autocompletes could be used, and of course there would have to be an exact term match.)

**Comment by DavidRoy** [comment]
I agree with Oli.  Perhaps in the first instance we just implement at the sample level.  At this level we can use the full VC name I assume

**Comment by johnvanbreda** [comment]
I've now enabled the vice county input at sample level. Let me know if that does the job. Yes - it uses the full VS name - as the population is automatic there are less advantages to using the VC number.

**Comment by DavidRoy** [comment]
Works well, thanks
